name: CI
on:
  push:
    branches:
      - master
  pull_request:

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#defining-access-for-the-github_token-scopes
permissions: write-all

env:
  IMAGE_NAME: ${{ github.repository_owner }}/push-to-ghcr

jobs:
  ghcr:
    runs-on: "ubuntu-latest"  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on 

    steps:
      - uses: actions/checkout@v4

      - name: Run an action
        uses: ./
        with:
          image_name: ${{ env.IMAGE_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: foo_tag

      - name: Make sure that an image has been built and tagged properly
        env:
          IMAGE: ghcr.io/${{ env.IMAGE_NAME }}
        run: |
          docker images | grep ${IMAGE}
          docker images | grep foo_tag

      - name: Make sure that an image has been pushed and is properly labelled
        env:
          IMAGE: ghcr.io/${{ env.IMAGE_NAME }}
        run: |
          set -x
          docker rmi ${IMAGE}:foo_tag
          docker pull ${IMAGE}:foo_tag
          docker image inspect ${IMAGE}:foo_tag | jq '.[].Config.Labels' | tee /dev/fd/2 | grep "${GITHUB_SHA}"

  ghcr_with_extra_args:
    runs-on: "ubuntu-latest"  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on 

    steps:
      - uses: actions/checkout@v4

      - name: Run an action
        uses: ./
        with:
          image_name: ${{ env.IMAGE_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: foo_tag
          # use this input to pass extra arguments to 'docker build'
          extra_args: '--label extra-args-test=foo'

      - name: Make sure that an image has been built and tagged properly
        env:
          IMAGE: ghcr.io/${{ env.IMAGE_NAME }}
        run: |
          set -x
          docker images | grep ${IMAGE}
          docker images | grep foo_tag
          docker image inspect ${IMAGE}:foo_tag | jq '.[].Config.Labels' | tee /dev/fd/2 | grep '"extra-args-test": "foo"'

  ghcr_and_docker_io_with_multiple_image_tags:
    runs-on: "ubuntu-latest"  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - uses: actions/checkout@v4

      - name: Run an action
        uses: ./
        with:
          image_name: "${{ env.IMAGE_NAME }}-multi"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: 'multi_tag_primary, multi_tag_latest'
          docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}  # see https://hub.docker.com/settings/security

      - name: Make sure that all image tags have been built and pushed
        env:
          IMAGE: ${{ env.IMAGE_NAME }}-multi
        run: |
          set -x
          docker images | grep ghcr.io/${IMAGE}
          docker images | grep multi_tag_primary
          docker images | grep multi_tag_latest
          docker image inspect ghcr.io/${IMAGE}:multi_tag_primary
          docker image inspect ghcr.io/${IMAGE}:multi_tag_latest
          docker image inspect docker.io/${IMAGE}:multi_tag_primary
          docker image inspect docker.io/${IMAGE}:multi_tag_latest

          docker rmi ghcr.io/${IMAGE}:multi_tag_primary
          docker rmi ghcr.io/${IMAGE}:multi_tag_latest
          docker rmi docker.io/${IMAGE}:multi_tag_primary
          docker rmi docker.io/${IMAGE}:multi_tag_latest

          docker pull ghcr.io/${IMAGE}:multi_tag_primary
          docker pull ghcr.io/${IMAGE}:multi_tag_latest
          docker pull docker.io/${IMAGE}:multi_tag_primary
          docker pull docker.io/${IMAGE}:multi_tag_latest

          docker image inspect ghcr.io/${IMAGE}:multi_tag_primary | jq '.[].Config.Labels' | tee /dev/fd/2 | grep "${GITHUB_SHA}"
          docker image inspect ghcr.io/${IMAGE}:multi_tag_latest | jq '.[].Config.Labels' | tee /dev/fd/2 | grep "${GITHUB_SHA}"
          docker image inspect docker.io/${IMAGE}:multi_tag_primary | jq '.[].Config.Labels' | tee /dev/fd/2 | grep "${GITHUB_SHA}"
          docker image inspect docker.io/${IMAGE}:multi_tag_latest | jq '.[].Config.Labels' | tee /dev/fd/2 | grep "${GITHUB_SHA}"

  ghcr_with_multiple_image_tags_newline:
    runs-on: "ubuntu-latest"  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - uses: actions/checkout@v4

      - name: Run an action
        uses: ./
        with:
          image_name: "${{ env.IMAGE_NAME }}-multi-newline"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: |
            multi_tag_newline_primary
            multi_tag_newline_latest

      - name: Make sure that all image tags have been built
        env:
          IMAGE: ghcr.io/${{ env.IMAGE_NAME }}-multi-newline
        run: |
          docker image inspect ${IMAGE}:multi_tag_newline_primary
          docker image inspect ${IMAGE}:multi_tag_newline_latest

  ghcr_with_dockerfile_in_subdir:
    runs-on: "ubuntu-latest"  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - uses: actions/checkout@v4

      - name: Run an action
        uses: ./
        with:
          image_name: "foo/bar-app"
          dockerfile: "./foo/bar/Dockerfile"
          context: "./foo"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make sure that an image has been built
        env:
          IMAGE: ghcr.io/foo/bar-app
        run: |
          set -x
          docker images | grep ${IMAGE}
          docker image inspect ${IMAGE} | jq '.[].Config.Labels' | tee /dev/fd/2 | grep "${GITHUB_SHA}"

  ghcr_and_docker_io:
    runs-on: "ubuntu-latest"  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - uses: actions/checkout@v4

      - name: Run an action
        uses: ./
        with:
          image_name: ${{ env.IMAGE_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}  # see https://hub.docker.com/settings/security

      - name: Make sure that an image has been built
        env:
          IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          docker images | grep ${IMAGE}

      - name: Make sure that an image has been pushed and is properly labelled
        env:
          IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          set -x
          docker rmi ghcr.io/${IMAGE}
          docker rmi docker.io/${IMAGE}

          docker pull ghcr.io/${IMAGE}
          docker pull docker.io/${IMAGE}

          docker image inspect ghcr.io/${IMAGE} | jq '.[].Config.Labels' | tee /dev/fd/2 | grep "${GITHUB_SHA}"
          docker image inspect docker.io/${IMAGE} | jq '.[].Config.Labels' | tee /dev/fd/2 | grep "${GITHUB_SHA}"
